apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangamdashboard
  namespace: webapps
  labels:
    app: sangamdashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sangamdashboard
  template:
    metadata:
      labels:
        app: sangamdashboard
    spec:
      containers:
      - name: sangamdashboard-container
        image: praveenkumar90400/sangamdashboard:latest
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: sangamdashboard-service
spec:
  selector:
    app: sangamdashboard
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
