version: '3.8'

services:
  app:
    build: .
    container_name: sangamdashboard
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: kubernetes
      DB_DATABASE: my_sql
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
