version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_sql
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
