version: '3.8'

services:
  app:
    build: .
    container_name: sangamdashboard
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: your-db-host
      DB_DATABASE: your-db-name
      DB_USERNAME: your-db-user
      DB_PASSWORD: your-db-password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
