version: '3.8'

services:
  app:
    image: praveenkumar90400/sangamdashboard:latest
    container_name: sangamdashboard
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: SangamDB
      DB_USERNAME: praveen
      DB_PASSWORD: sangam@2025

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: SangamDB
      MYSQL_ROOT_PASSWORD: sangam@2025
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
