apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangamdashboard
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sangamdashboard
  template:
    metadata:
      labels:
        app: sangamdashboard
    spec:
      containers:
      - name: sangamdashboard
        image: praveenkumar90400/sangamdashboard:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: sangamdashboard
  namespace: webapps
spec:
  selector:
    app: sangamdashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
