apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangamdashboard
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: sangamdashboard
  replicas: 3
  template:
    metadata:
      labels:
        app: sangamdashboard
    spec:
      containers:
      - name: sangamdashboard-container
        image: praveenkumar90400/sangamdashboard:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: sangamdashboard-service
spec:
  ports:
  - port: 80
  selector:
    app: sangamdashboard
  type: LoadBalancer
