apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 1
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: your-docker-registry/your-laravel-app
        ports:
        - containerPort: 80
        env:
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  ports:
  - port: 80
  selector:
    app: laravel
  type: ClusterIP
