apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_DATABASE: U2FuZ2FtREI=    # Base64 encoded value of 'SangamDB'
  DB_USERNAME: cHJhdmVlbg==    # Base64 encoded value of 'praveen'
  DB_PASSWORD: c2FuZ2FtQDIwMjU= # Base64 encoded value of 'sangam@2025'
